[GLOBAL]
pants_version = "2.21.0dev6"
backend_packages = [
	"pants.backend.python",
	"pants.backend.experimental.python",
	"pants.backend.experimental.python.lint.ruff.check",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.lint.autoflake",
	"pants.backend.python.lint.pylint",
	"pants.backend.python.typecheck.mypy",
	"pants.backend.experimental.adhoc",
]

[source]
root_patterns = [
	"src/main/python",
	"src/it/python",
	"src/it/resources",
	"examples/src/main/python",
]

[python]
interpreter_constraints = ["CPython>=3.10"]
enable_resolves = true

[python.resolves]
python-default = "cicd/python-default.lock"
mypy = "cicd/mypy.lock"

[pylint]
config = ".pylintrc"

[flake8]
config = ".flake8"

[test]
use_coverage = true
extra_env_vars = ["integration_test_secrets", "INTEGRATION_PRINT_OUTPUT", "AZURE_CONFIG_DIR", "DOCKER_HOST"]

[coverage-py]
report = ["xml", "html"]

[mypy]
install_from_resolve = "mypy"
requirements = ["//:mypy"]
interpreter_constraints = ["CPython>=3.10"]
