# Lint tests run on PR
# but should not run after push to main because reporting
# these after push is meaningless to the building of the package
name: lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pantsbuild/actions/init-pants@v5-scie-pants
        with:
          # v0 makes it easy to bust the cache if needed
          # just increase the integer to start with a fresh cache
          gha-cache-key: v0
          named-caches-hash: ${{ hashFiles('cicd/python-default.lock') }}
          cache-lmdb-store: 'true'

      - name: Upload pants log
        uses: actions/upload-artifact@v4
        with:
          name: pants-log-lint
          path: .pants.d/pants.log
        if: always() # We want the log even on failures.
